from pathlib import Path
p=Path('/mnt/data/vido_upgrade/index.html')
s=p.read_text()
# Add adaptive panel to progress
marker='<div class="card"><h3 id="skillsTitle">Skills</h3><div class="list" id="skillList"></div></div>'
if 'id="adaptiveDue"' not in s:
    add='<div class="card" style="margin-top:14px"><h3 data-i18n="adaptive_title">Adaptive Learning & Spaced Repetition</h3><div class="metrics"><div class="metric"><span class="muted" data-i18n="adaptive_due">Fällige Reviews</span><b id="adaptiveDue">0</b></div><div class="metric"><span class="muted" data-i18n="adaptive_next">Nächste Auswahl</span><b id="adaptiveNext">—</b></div></div><button class="primary" id="adaptiveStart" style="margin-top:10px" data-i18n="adaptive_start">Adaptive Aufgabe starten</button></div>'
    s=s.replace(marker,marker+add)
# Add data-i18n labels are updated by V2 helper. Replace engine block entirely to add helper and adaptive UI.
start=s.find('<style id="vido-v2-engine">'); end=s.find('</script>\n</body></html>',start)
end += len('</script>')
engine=r'''<style id="vido-v2-engine">
.tutorStatus{font-size:12px}.engineBadge{font-size:11px;border:1px solid var(--line);border-radius:99px;padding:5px 9px;background:#0b1726;color:#b7c8d9}.healthOk{color:#4ade80}.healthWarn{color:#fbbf24}.accountGrid{display:grid;grid-template-columns:1fr 1fr;gap:14px}@media(max-width:650px){.accountGrid{grid-template-columns:1fr}}
</style>
<script>
(function(){
  const API_BASE=window.VIDO_API_BASE||'/api';
  const engineState=JSON.parse(localStorage.getItem('vidoEngineV2')||'{}');
  engineState.review=engineState.review||{};engineState.answerStartedAt=engineState.answerStartedAt||Date.now();engineState.sessionEvents=engineState.sessionEvents||[];engineState.token=engineState.token||null;engineState.sim=engineState.sim||{devices:[],links:[],arp:{},mac:{},routes:[{network:'192.168.10.0/24',nextHop:'connected',interface:'G0/0'},{network:'0.0.0.0/0',nextHop:'192.168.10.254',interface:'G0/0'}]};
  const persist=()=>localStorage.setItem('vidoEngineV2',JSON.stringify(engineState));
  const api=(path,opts={})=>fetch(API_BASE+path,{...opts,headers:{'content-type':'application/json',...(opts.headers||{}),...(engineState.token?{authorization:'Bearer '+engineState.token}:{})}});
  const dueDate=d=>new Date(Date.now()+d*86400000).toISOString();
  function updateReview(q,correct){let r=engineState.review[q.id]||{interval:0,reps:0,ease:2.5,next:null,mastery:0};if(correct){r.reps++;r.interval=r.reps===1?1:r.reps===2?3:Math.max(1,Math.round(r.interval*r.ease));r.ease=Math.min(3,r.ease+.1);r.mastery=Math.min(100,r.mastery+12)}else{r.interval=0;r.ease=Math.max(1.3,r.ease-.2);r.mastery=Math.max(0,r.mastery-8)}r.next=dueDate(r.interval);engineState.review[q.id]=r;persist();return r}
  function recordEvent(q,correct){const ms=Math.max(0,Date.now()-engineState.answerStartedAt),hints=(state.hints&&state.hints[q.id])||0;updateReview(q,correct);engineState.sessionEvents.push({questionId:q.id,skill:q.skill,correct,answerTimeMs:ms,hintsUsed:hints,at:new Date().toISOString()});engineState.answerStartedAt=Date.now();persist();api('/events',{method:'POST',body:JSON.stringify({questionId:q.id,skill:q.skill,correct,answerTimeMs:ms,hintsUsed:hints})}).catch(()=>{})}
  window.vidoEngine={updateReview,recordEvent,engineState,persist};
  window.vidoNextAdaptive=function(){const now=Date.now(),due=Q.filter(q=>engineState.review[q.id]?.next&&Date.parse(engineState.review[q.id].next)<=now);if(due.length)return due[Math.floor(Math.random()*due.length)];const weak=Q.slice().sort((a,b)=>(state.mastery[a.skill]||0)-(state.mastery[b.skill]||0));return weak[Math.floor(Math.random()*Math.min(12,weak.length))]||Q[0]};
  function dueCount(){return Q.filter(q=>engineState.review[q.id]?.next&&Date.parse(engineState.review[q.id].next)<=Date.now()).length}
  function renderAdaptive(){if($('adaptiveDue'))$('adaptiveDue').textContent=dueCount();if($('adaptiveNext'))$('adaptiveNext').textContent=(vidoNextAdaptive()?.id)||'—'}
  $('adaptiveStart')?.addEventListener('click',()=>{const q=vidoNextAdaptive();const i=Q.findIndex(x=>x.id===q.id);if(i>=0){state.current=i;setRoute('learn')}});
  renderAdaptive();

  function tutorContext(){const q=Q[state.current]||Q[0];if($('tutorQuestion'))$('tutorQuestion').textContent=qTarget(q)+' · '+q.ip;if($('tutorSkill'))$('tutorSkill').textContent=qSkill(q)+' · '+levelLabel(q.level)}
  function tutorAsk(){const q=Q[state.current]||Q[0],input=$('tutorInput')?.value.trim()||'';const fallback=lang==='ar'?`ابدأ بقاعدة ${q.skill}. لا أعطيك الجواب مباشرة. حدد أول معلومة مطلوبة ثم طبق القاعدة خطوة بخطوة.`:lang==='en'?`Start with the ${q.skill} rule. I will not reveal the answer immediately. Identify the first required datum and apply the rule step by step.`:`Starte mit der Regel ${q.skill}. Ich verrate die Lösung nicht sofort. Bestimme zuerst die benötigte Information und wende die Regel Schritt für Schritt an.`;if($('tutorResponse'))$('tutorResponse').textContent=fallback;api('/tutor',{method:'POST',body:JSON.stringify({question:qTarget(q)+' | '+q.ip,answer:input,skill:q.skill,level:q.level,hintsUsed:(state.hints&&state.hints[q.id])||0,language:lang})}).then(async r=>{if(!r.ok)throw new Error();return r.json()}).then(d=>{if(d.reply)$('tutorResponse').textContent=d.reply}).catch(()=>{})}
  $('tutorAsk')?.addEventListener('click',tutorAsk);document.querySelectorAll('[data-route="tutor"]').forEach(b=>b.addEventListener('click',()=>setTimeout(tutorContext,0)));
  $('check')?.addEventListener('click',()=>{const q=Q[state.current],a=$('answer').value.trim();if(!a)return;const key=q.id+'|'+state.attempts;if(engineState.lastRecorded!==key){engineState.lastRecorded=key;recordEvent(q,grade(q,a));renderAdaptive()}tutorContext()});

  function ip4(s){const a=String(s).trim().split('.').map(Number);return a.length===4&&a.every(x=>Number.isInteger(x)&&x>=0&&x<=255)?a:null}
  function maskBits(mask){const a=ip4(mask);if(!a)return null;const b=a.map(x=>x.toString(2).padStart(8,'0')).join('');return b.includes('01')?null:(b.match(/1/g)||[]).length}
  function net(ip,mask){const a=ip4(ip),m=ip4(mask);return a&&m?a.map((x,i)=>x&m[i]).join('.'):null}
  function sameSubnet(a,b,mask){return net(a,mask)&&net(a,mask)===net(b,mask)}
  function simPing(){const ip=$('simIp').value.trim(),mask=$('simMask').value.trim(),gw=$('simGw').value.trim(),valid=!!ip4(ip)&&!!ip4(gw)&&maskBits(mask)!==null,ok=valid&&sameSubnet(ip,gw,mask);const msg=ok?(lang==='ar'?'✓ Ping ناجح: العنوان والـGateway في نفس الـSubnet.':lang==='en'?'✓ Ping successful: host and gateway are in the same subnet.':'✓ Ping erfolgreich: Host und Gateway liegen im selben Subnetz.'):(lang==='ar'?'✗ Ping فشل: افحص IP وSubnet Mask وGateway.':lang==='en'?'✗ Ping failed: check IP, subnet mask and gateway.':'✗ Ping fehlgeschlagen: IP, Subnetzmaske und Gateway prüfen.');simLog(msg);engineState.sim.lastPing={ip,mask,gw,ok};persist()}
  if($('simPing'))$('simPing').onclick=simPing;
  document.querySelectorAll('[data-add]').forEach(b=>{b.onclick=()=>{const n=engineState.sim.devices.length+1,d={id:b.dataset.add+'-'+n,type:b.dataset.add,ip:'',mask:'',gateway:'',mac:'AA:BB:CC:'+String(n).padStart(2,'0')+':00:01'};engineState.sim.devices.push(d);persist();simLog((lang==='ar'?'تمت إضافة ':lang==='en'?'Added ':'Hinzugefügt ')+d.id)}});
  if($('cliIn'))$('cliIn').onkeydown=e=>{if(e.key!=='Enter')return;const c=e.target.value.trim(),o=$('cliOut');o.textContent+=`\nVIDO-R1# ${c}`;const known={'show ip interface brief':'Gig0/0  192.168.10.1  up  up\nGig0/1  10.0.0.1      up  up','show ip route':'C 192.168.10.0/24 is directly connected, Gig0/0\nS* 0.0.0.0/0 via 192.168.10.254','show arp':'192.168.10.10  AA:BB:CC:10:10:10  ARPA','show mac address-table':'10  AA:BB:CC:10:10:10  DYNAMIC  Gi0/1','no shutdown':'Interface enabled','ip address 192.168.1.1 255.255.255.0':'Interface IPv4 configured'};o.textContent+='\n'+(known[c]||'% VIDO training mode: command not implemented. Try show ip route, show arp, show mac address-table, show ip interface brief, no shutdown.');e.target.value=''};

  function accountStatus(msg){if($('accountStatus'))$('accountStatus').textContent=msg}
  async function register(){const email=$('accountEmail').value.trim(),password=$('accountPassword').value;const r=await api('/auth/register',{method:'POST',body:JSON.stringify({email,password})});const d=await r.json();if(!r.ok)return accountStatus(d.error||'Registration failed');engineState.token=d.token;persist();accountStatus('Registered and signed in.');sync()}
  async function login(){const email=$('accountEmail').value.trim(),password=$('accountPassword').value;const r=await api('/auth/login',{method:'POST',body:JSON.stringify({email,password})});const d=await r.json();if(!r.ok)return accountStatus(d.error||'Login failed');engineState.token=d.token;persist();accountStatus('Signed in.');sync()}
  async function sync(){if(!engineState.token)return accountStatus('Sign in first.');const r=await api('/state');if(r.ok){const remote=await r.json();if(remote){Object.assign(state,remote);save();renderStats();renderQuestion();renderLists();renderProgress()}}await api('/state',{method:'PUT',body:JSON.stringify({state})});accountStatus('Cloud sync completed.')}
  $('accountRegister')?.addEventListener('click',register);$('accountLogin')?.addEventListener('click',login);$('accountSync')?.addEventListener('click',sync);

  const labels={de:{tutor:'✦ VIDO Tutor',account:'◉ Account & Sync',tutor_title:'VIDO Tutor',tutor_subtitle:'Sokratischer IT-Lernassistent',tutor_context:'Aktuelle Aufgabe',tutor_ask:'Tutor fragen',tutor_response:'Tutor-Antwort',account_title:'Account & Sync',adaptive_title:'Adaptives Lernen & Spaced Repetition',adaptive_due:'Fällige Reviews',adaptive_next:'Nächste Auswahl',adaptive_start:'Adaptive Aufgabe starten'},en:{tutor:'✦ VIDO Tutor',account:'◉ Account & Sync',tutor_title:'VIDO Tutor',tutor_subtitle:'Socratic IT learning assistant',tutor_context:'Current task',tutor_ask:'Ask Tutor',tutor_response:'Tutor response',account_title:'Account & Sync',adaptive_title:'Adaptive Learning & Spaced Repetition',adaptive_due:'Reviews due',adaptive_next:'Next selection',adaptive_start:'Start adaptive task'},ar:{tutor:'✦ مساعد VIDO',account:'◉ الحساب والمزامنة',tutor_title:'مساعد VIDO',tutor_subtitle:'مساعد تعليمي لتقنية المعلومات بطريقة سقراطية',tutor_context:'السؤال الحالي',tutor_ask:'اسأل المساعد',tutor_response:'رد المساعد',account_title:'الحساب والمزامنة',adaptive_title:'التعلم التكيفي والتكرار المتباعد',adaptive_due:'المراجعات المستحقة',adaptive_next:'الاختيار التالي',adaptive_start:'بدء سؤال تكيفي'}};
  function updateV2Labels(){const l=labels[lang]||labels.de;document.querySelectorAll('[data-route="tutor"]').forEach(b=>b.textContent=l.tutor);document.querySelectorAll('[data-route="account"]').forEach(b=>b.textContent=l.account);const map={tutor_title:'tutor_title',tutor_subtitle:'tutor_subtitle',tutor_context:'tutor_context',tutor_ask:'tutor_ask',tutor_response:'tutor_response',account_title:'account_title',adaptive_title:'adaptive_title',adaptive_due:'adaptive_due',adaptive_next:'adaptive_next',adaptive_start:'adaptive_start'};Object.entries(map).forEach(([id,k])=>{const e=document.querySelector('[data-i18n="'+id+'"]');if(e)e.textContent=l[k]});if($('accountEmail'))$('accountEmail').placeholder=lang==='ar'?'البريد الإلكتروني':lang==='en'?'Email':'E-Mail';if($('accountPassword'))$('accountPassword').placeholder=lang==='ar'?'كلمة المرور (8 أحرف على الأقل)':lang==='en'?'Password (8+ characters)':'Passwort (8+ Zeichen)';renderAdaptive()}
  $('langSelect')?.addEventListener('change',()=>setTimeout(updateV2Labels,0));updateV2Labels();
  const badge=document.createElement('span');badge.className='engineBadge';badge.textContent='Engine';document.querySelector('.top')?.appendChild(badge);api('/health').then(r=>r.json()).then(h=>{badge.textContent=h.database&&h.ai?'Backend + AI ✓':h.database?'Backend ✓':'Local Engine';badge.className='engineBadge '+(h.database?'healthOk':'healthWarn')}).catch(()=>{badge.textContent='Local Engine'});
  document.documentElement.dataset.vidoEngine='v2';
})();
</script>'''
s=s[:start]+engine+s[end:]
p.write_text(s)
