
(function(){
  const core=window.vidoCore;
  if(!core){console.error('[VIDO] Core engine bridge unavailable');return;}
  const Q=core.Q;
  const state=core.state;
  const $=core.$;
  const qTarget=core.qTarget;
  const qSkill=core.qSkill;
  const levelLabel=core.levelLabel;
  const save=core.save;
  const renderStats=core.renderStats;
  const renderQuestion=core.renderQuestion;
  const renderLists=core.renderLists;
  const renderProgress=core.renderProgress;
  const setRoute=core.setRoute;
  const API_BASE=window.VIDO_API_BASE||'/api';
  const engineState=JSON.parse(sessionStorage.getItem('vidoEngineV2')||'{}');
  engineState.review=engineState.review||{};engineState.answerStartedAt=engineState.answerStartedAt||Date.now();engineState.sessionEvents=engineState.sessionEvents||[];engineState.token=engineState.token||null;engineState.sim=engineState.sim||{devices:[],links:[],arp:{},mac:{},routes:[{network:'192.168.10.0/24',nextHop:'connected',interface:'G0/0'},{network:'0.0.0.0/0',nextHop:'192.168.10.254',interface:'G0/0'}]};
  const persist=()=>sessionStorage.setItem('vidoEngineV2',JSON.stringify(engineState));
  const api=(path,opts={})=>fetch(API_BASE+path,{...opts,headers:{'content-type':'application/json',...(opts.headers||{}),...(engineState.token?{authorization:'Bearer '+engineState.token}:{})}});
  const dueDate=d=>new Date(Date.now()+d*86400000).toISOString();
  function updateReview(q,correct){let r=engineState.review[q.id]||{interval:0,reps:0,ease:2.5,next:null,mastery:0};if(correct){r.reps++;r.interval=r.reps===1?1:r.reps===2?3:Math.max(1,Math.round(r.interval*r.ease));r.ease=Math.min(3,r.ease+.1);r.mastery=Math.min(100,r.mastery+12)}else{r.interval=0;r.ease=Math.max(1.3,r.ease-.2);r.mastery=Math.max(0,r.mastery-8)}r.next=dueDate(r.interval);engineState.review[q.id]=r;persist();return r}
  function recordEvent(q,correct){const ms=Math.max(0,Date.now()-engineState.answerStartedAt),hints=(state.hints&&state.hints[q.id])||0;updateReview(q,correct);engineState.sessionEvents.push({questionId:q.id,skill:q.skill,correct,answerTimeMs:ms,hintsUsed:hints,at:new Date().toISOString()});engineState.answerStartedAt=Date.now();persist();api('/events',{method:'POST',body:JSON.stringify({questionId:q.id,skill:q.skill,correct,answerTimeMs:ms,hintsUsed:hints})}).catch(()=>{})}
  window.vidoEngine={updateReview,recordEvent,engineState,persist};
  window.vidoNextAdaptive=function(){const now=Date.now(),due=Q.filter(q=>engineState.review[q.id]?.next&&Date.parse(engineState.review[q.id].next)<=now);if(due.length)return due[Math.floor(Math.random()*due.length)];const weak=Q.slice().sort((a,b)=>(state.mastery[a.skill]||0)-(state.mastery[b.skill]||0));return weak[Math.floor(Math.random()*Math.min(12,weak.length))]||Q[0]};
  function dueCount(){return Q.filter(q=>engineState.review[q.id]?.next&&Date.parse(engineState.review[q.id].next)<=Date.now()).length}
  function renderAdaptive(){if($('adaptiveDue'))$('adaptiveDue').textContent=dueCount();if($('adaptiveNext'))$('adaptiveNext').textContent=(vidoNextAdaptive()?.id)||'—'}
  $('adaptiveStart')?.addEventListener('click',()=>{const q=vidoNextAdaptive();const i=Q.findIndex(x=>x.id===q.id);if(i>=0){state.current=i;setRoute('learn')}});
  renderAdaptive();

  function tutorContext(){const q=Q[state.current]||Q[0];if($('tutorQuestion'))$('tutorQuestion').textContent=qTarget(q)+' · '+q.ip;if($('tutorSkill'))$('tutorSkill').textContent=qSkill(q)+' · '+levelLabel(q.level)}
  function tutorAsk(){const q=Q[state.current]||Q[0],input=$('tutorInput')?.value.trim()||'';const fallback=lang==='ar'?`ابدأ بقاعدة ${q.skill}. لا أعطيك الجواب مباشرة. حدد أول معلومة مطلوبة ثم طبق القاعدة خطوة بخطوة.`:lang==='en'?`Start with the ${q.skill} rule. I will not reveal the answer immediately. Identify the first required datum and apply the rule step by step.`:`Starte mit der Regel ${q.skill}. Ich verrate die Lösung nicht sofort. Bestimme zuerst die benötigte Information und wende die Regel Schritt für Schritt an.`;if($('tutorResponse'))$('tutorResponse').textContent=fallback;api('/tutor',{method:'POST',body:JSON.stringify({question:qTarget(q)+' | '+q.ip,answer:input,skill:q.skill,level:q.level,hintsUsed:(state.hints&&state.hints[q.id])||0,language:lang})}).then(async r=>{if(!r.ok)throw new Error();return r.json()}).then(d=>{if(d.reply)$('tutorResponse').textContent=d.reply}).catch(()=>{})}
  $('tutorAsk')?.addEventListener('click',tutorAsk);document.querySelectorAll('[data-route="tutor"]').forEach(b=>b.addEventListener('click',()=>setTimeout(tutorContext,0)));
  $('check')?.addEventListener('click',()=>{const q=Q[state.current],a=$('answer').value.trim();if(!a)return;const key=q.id+'|'+state.attempts;if(engineState.lastRecorded!==key){engineState.lastRecorded=key;recordEvent(q,grade(q,a));renderAdaptive()}tutorContext()});

  function ip4(s){const a=String(s).trim().split('.').map(Number);return a.length===4&&a.every(x=>Number.isInteger(x)&&x>=0&&x<=255)?a:null}
  function maskBits(mask){const a=ip4(mask);if(!a)return null;const b=a.map(x=>x.toString(2).padStart(8,'0')).join('');return b.includes('01')?null:(b.match(/1/g)||[]).length}
  function net(ip,mask){const a=ip4(ip),m=ip4(mask);return a&&m?a.map((x,i)=>x&m[i]).join('.'):null}
  function sameSubnet(a,b,mask){return net(a,mask)&&net(a,mask)===net(b,mask)}
  function simPing(){const ip=$('simIp').value.trim(),mask=$('simMask').value.trim(),gw=$('simGw').value.trim(),valid=!!ip4(ip)&&!!ip4(gw)&&maskBits(mask)!==null,ok=valid&&sameSubnet(ip,gw,mask);const msg=ok?(lang==='ar'?'✓ Ping ناجح: العنوان والـGateway في نفس الـSubnet.':lang==='en'?'✓ Ping successful: host and gateway are in the same subnet.':'✓ Ping erfolgreich: Host und Gateway liegen im selben Subnetz.'):(lang==='ar'?'✗ Ping فشل: افحص IP وSubnet Mask وGateway.':lang==='en'?'✗ Ping failed: check IP, subnet mask and gateway.':'✗ Ping fehlgeschlagen: IP, Subnetzmaske und Gateway prüfen.');simLog(msg);engineState.sim.lastPing={ip,mask,gw,ok};persist()}
  if($('simPing'))$('simPing').onclick=simPing;
  document.querySelectorAll('[data-add]').forEach(b=>{b.onclick=()=>{const n=engineState.sim.devices.length+1,d={id:b.dataset.add+'-'+n,type:b.dataset.add,ip:'',mask:'',gateway:'',mac:'AA:BB:CC:'+String(n).padStart(2,'0')+':00:01'};engineState.sim.devices.push(d);persist();simLog((lang==='ar'?'تمت إضافة ':lang==='en'?'Added ':'Hinzugefügt ')+d.id)}});
  if($('cliIn'))$('cliIn').onkeydown=e=>{if(e.key!=='Enter')return;const c=e.target.value.trim(),o=$('cliOut');o.textContent+=`\nVIDO-R1# ${c}`;const known={'show ip interface brief':'Gig0/0  192.168.10.1  up  up\nGig0/1  10.0.0.1      up  up','show ip route':'C 192.168.10.0/24 is directly connected, Gig0/0\nS* 0.0.0.0/0 via 192.168.10.254','show arp':'192.168.10.10  AA:BB:CC:10:10:10  ARPA','show mac address-table':'10  AA:BB:CC:10:10:10  DYNAMIC  Gi0/1','no shutdown':'Interface enabled','ip address 192.168.1.1 255.255.255.0':'Interface IPv4 configured'};o.textContent+='\n'+(known[c]||'% VIDO training mode: command not implemented. Try show ip route, show arp, show mac address-table, show ip interface brief, no shutdown.');e.target.value=''};

  const authGate=$('authGate');
  let authRegisterMode=false;
  function gateStatus(msg){if($('gateMsg'))$('gateMsg').textContent=msg||''}
  function applyAuthGateText(){if(!$('authGate'))return;const m={title:t('auth_title'),sub:t('auth_sub'),email:t('auth_email'),password:t('auth_password'),login:t('auth_login'),admin:t('auth_admin'),hint:t('auth_hint'),register:t('auth_register'),confirm:t('auth_register_confirm'),back:t('auth_back_login')};$('authGateTitle').textContent=authRegisterMode?m.registerMode||m.register:m.title;$('authGateSub').textContent=authRegisterMode?m.registerMode||m.register:m.sub;$('gateEmail').placeholder=m.email;$('gatePassword').placeholder=m.password;$('gatePasswordConfirm').placeholder=m.confirm;$('gateLogin').textContent=m.login;$('gateAdmin').textContent=m.admin;$('gateRegister').textContent=authRegisterMode?m.back:m.register;$('gateHint').textContent=m.hint}
  function setLogoutVisible(show){const b=$('logoutBtn');if(b)b.classList.toggle('visible',!!show)}
  function unlockApp(user){engineState.token=engineState.token||null;engineState.role=user?.role||engineState.role||null;engineState.email=user?.email||engineState.email||null;persist();document.body.classList.remove('authLocked');if(authGate)authGate.hidden=true;setLogoutVisible(true);checkAdminAccess();}
  function logout(){engineState.token=null;engineState.role=null;engineState.email=null;engineState.review={};engineState.sessionEvents=[];engineState.lastRecorded=null;sessionStorage.removeItem('vidoEngineV2');document.body.classList.add('authLocked');if(authGate)authGate.hidden=false;showAdminButton(false);setLogoutVisible(false);if($('gatePassword'))$('gatePassword').value='';if($('gateMsg'))$('gateMsg').textContent='';if($('gateEmail'))$('gateEmail').value='';if($('gatePasswordConfirm'))$('gatePasswordConfirm').value='';authRegisterMode=false;applyAuthGateText();setRoute('home',false);}
  async function validateStoredSession(){if(!engineState.token){setLogoutVisible(false);return false}try{const r=await api('/auth/me');if(!r.ok)throw new Error();const d=await r.json();unlockApp(d.user);return true}catch{engineState.token=null;engineState.role=null;engineState.email=null;sessionStorage.setItem('vidoEngineV2',JSON.stringify(engineState));setLogoutVisible(false);return false}}
  async function gateLogin(){const email=$('gateEmail').value.trim(),password=$('gatePassword').value;if(!email||!password)return gateStatus(t('auth_failed'));gateStatus('');try{const r=await api('/auth/login',{method:'POST',body:JSON.stringify({email,password})});const d=await r.json();if(!r.ok)throw new Error(d.error||'login');engineState.token=d.token;engineState.role=d.user?.role||null;engineState.email=d.user?.email||email;unlockApp(d.user);accountStatus(lang==='ar'?'تم تسجيل الدخول.':lang==='en'?'Signed in.':'Angemeldet.');sync()}catch(e){gateStatus(t('auth_failed'))}}
  async function gateRegister(){const email=$('gateEmail').value.trim(),password=$('gatePassword').value,confirm=$('gatePasswordConfirm').value;if(!/^\S+@\S+\.\S+$/.test(email)||password.length<8||password!==confirm)return gateStatus(t('auth_register_failed'));gateStatus('');try{const r=await api('/auth/register',{method:'POST',body:JSON.stringify({email,password})});const d=await r.json();if(!r.ok)throw new Error(d.error||'register');engineState.token=d.token;engineState.role=d.user?.role||'user';engineState.email=d.user?.email||email;unlockApp(d.user);accountStatus(t('auth_register_success'));sync()}catch(e){gateStatus(e.message==='email already registered'?(lang==='ar'?'البريد الإلكتروني مستخدم مسبقًا.':lang==='en'?'Email is already registered.':'E-Mail ist bereits registriert.'):t('auth_register_failed'))}}
  function toggleAuthRegister(){authRegisterMode=!authRegisterMode;$('gatePasswordConfirm').hidden=!authRegisterMode;$('gateAdmin').hidden=authRegisterMode;$('gateLogin').hidden=authRegisterMode;$('gateRegister').textContent=authRegisterMode?t('auth_back_login'):t('auth_register');if(authRegisterMode){$('authGateTitle').textContent=t('auth_register_mode');$('authGateSub').textContent=t('auth_register_mode')}else{applyAuthGateText()}gateStatus('')}
  async function gateAdminLogin(){const password=$('gatePassword').value;if(!password)return gateStatus(t('auth_admin_failed'));gateStatus('');try{const r=await api('/auth/quick-admin',{method:'POST',body:JSON.stringify({username:($('gateEmail').value.trim()||'Admin'),password})});const d=await r.json();if(!r.ok)throw new Error(d.error||'admin');engineState.token=d.token;engineState.role='owner';engineState.email=d.user?.email||'admin';unlockApp(d.user);accountStatus(lang==='ar'?'تم تسجيل دخول Admin.':lang==='en'?'Admin signed in.':'Admin angemeldet.');sync()}catch(e){gateStatus(t('auth_admin_failed'))}}
  $('gateLogin')?.addEventListener('click',gateLogin);$('gateAdmin')?.addEventListener('click',gateAdminLogin);$('gateRegister')?.addEventListener('click',()=>authRegisterMode?gateRegister():toggleAuthRegister());$('logoutBtn')?.addEventListener('click',logout);$('gatePassword')?.addEventListener('keydown',e=>{if(e.key==='Enter')authRegisterMode?gateRegister():gateLogin()});$('gatePasswordConfirm')?.addEventListener('keydown',e=>{if(e.key==='Enter')gateRegister()});
  function accountStatus(msg){if($('accountStatus'))$('accountStatus').textContent=msg}
  async function register(){const email=$('accountEmail').value.trim(),password=$('accountPassword').value;const r=await api('/auth/register',{method:'POST',body:JSON.stringify({email,password})});const d=await r.json();if(!r.ok)return accountStatus(d.error||'Registration failed');engineState.token=d.token;engineState.role=d.user?.role||null;engineState.email=d.user?.email||email;persist();checkAdminAccess();accountStatus(lang==='ar'?'تم إنشاء الحساب وتسجيل الدخول.':lang==='en'?'Registered and signed in.':'Registriert und angemeldet.');sync()}
  async function login(){const email=$('accountEmail').value.trim(),password=$('accountPassword').value;const r=await api('/auth/login',{method:'POST',body:JSON.stringify({email,password})});const d=await r.json();if(!r.ok)return accountStatus(d.error||'Login failed');engineState.token=d.token;engineState.role=d.user?.role||null;engineState.email=d.user?.email||email;persist();checkAdminAccess();accountStatus(lang==='ar'?'تم تسجيل الدخول.':lang==='en'?'Signed in.':'Angemeldet.');sync()}
  async function sync(){if(!engineState.token)return accountStatus(lang==='ar'?'سجّل الدخول أولًا.':lang==='en'?'Sign in first.':'Bitte zuerst anmelden.');const r=await api('/state');if(r.ok){const remote=await r.json();if(remote){Object.assign(state,remote);save();renderStats();renderQuestion();renderLists();renderProgress()}}await api('/state',{method:'PUT',body:JSON.stringify({state})});accountStatus('Cloud sync completed.')}
  $('accountRegister')?.addEventListener('click',register);$('accountLogin')?.addEventListener('click',login);$('accountSync')?.addEventListener('click',sync);

  function showAdminButton(show){document.querySelectorAll('.adminOnly').forEach(b=>b.hidden=!show)}
  function escHtml(v){return String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
  function adminText(){return {de:{title:'👑 VIDO Owner Control Center',users:'Benutzer',active:'Aktiv 15 Min.',activity:'Aktivität 24 Std.',failed:'Fehlgeschlagene Logins 24 Std.',usersBtn:'Benutzer',create:'+ Benutzer erstellen',activityBtn:'Aktivität',security:'Sicherheit',audit:'Audit',system:'System',refresh:'↻ Aktualisieren'},en:{title:'👑 VIDO Owner Control Center',users:'Users',active:'Active 15m',activity:'Activity 24h',failed:'Failed Logins 24h',usersBtn:'Users',create:'+ Create User',activityBtn:'Activity',security:'Security',audit:'Audit',system:'System',refresh:'↻ Refresh'},ar:{title:'👑 مركز تحكم مالك VIDO',users:'المستخدمون',active:'نشط خلال 15 دقيقة',activity:'النشاط خلال 24 ساعة',failed:'تسجيلات الدخول الفاشلة 24 ساعة',usersBtn:'المستخدمون',create:'+ إنشاء مستخدم',activityBtn:'النشاط',security:'الأمان',audit:'السجل الإداري',system:'النظام',refresh:'↻ تحديث'}}[lang]||null}
  function updateAdminLabels(){const l=adminText();if(!l)return;const m={adminTitle:'title',adminUsersLabel:'users',adminActiveLabel:'active',adminActivityLabel:'activity',adminFailedLabel:'failed',adminUsersBtn:'usersBtn',adminCreateBtn:'create',adminActivityBtn:'activityBtn',adminSecurityBtn:'security',adminAuditBtn:'audit',adminSystemBtn:'system',adminRefresh:'refresh'};Object.entries(m).forEach(([id,k])=>{const e=$(id);if(e)e.textContent=l[k]})}
  async function adminFetch(path,opts={}){const r=await api(path,opts);if(r.status===403||r.status===401){showAdminButton(false);throw new Error('forbidden')}return r}
  function adminTable(headers,rows){return `<div style="overflow:auto"><table class="adminTable"><thead><tr>${headers.map(h=>`<th>${escHtml(h)}</th>`).join('')}</tr></thead><tbody>${rows.map(row=>`<tr>${row.map(c=>`<td>${c}</td>`).join('')}</tr>`).join('')}</tbody></table></div>`}
  function adminNotice(msg,kind=''){const el=$('adminPanel');if(el)el.innerHTML=`<div class="feedback ${kind}">${escHtml(msg)}</div>`}
  async function loadAdminOverview(){const r=await adminFetch('/admin/overview');if(!r.ok)throw new Error();const d=await r.json();$('adminUsers').textContent=d.users;$('adminActive').textContent=d.active15m;$('adminActivity').textContent=d.activity24h;$('adminFailed').textContent=d.failedLogins24h;$('adminRole').textContent=String(d.role||'ADMIN').toUpperCase();showAdminButton(true);updateAdminLabels()}
  function roleOptions(selected='user'){return ['user','analyst','content_manager','video_manager','lab_manager','super_admin','owner'].map(r=>`<option value="${r}" ${r===selected?'selected':''}>${r}</option>`).join('')}
  async function loadAdminUsers(){const r=await adminFetch('/admin/users');const d=await r.json();const owner=String($('adminRole')?.textContent||'').toLowerCase()==='owner';const rows=d.map(u=>{const actions=owner?`<select data-role-user="${escHtml(u.id)}" class="adminSelect">${roleOptions(u.role)}</select><button class="miniBtn" data-status-user="${escHtml(u.id)}" data-status="${u.status==='active'?'suspended':'active'}">${u.status==='active'?'Suspend':'Activate'}</button><button class="miniBtn" data-reset-user="${escHtml(u.id)}">Reset PW</button>${u.email===engineState?.email?'':'<button class="miniBtn danger" data-delete-user="'+escHtml(u.id)+'">Delete</button>'}`:'View only';return [escHtml(u.email),escHtml(u.role),escHtml(u.status),new Date(u.created_at).toLocaleString(),u.last_login_at?new Date(u.last_login_at).toLocaleString():'—',escHtml(u.last_ip||'—'),escHtml(u.last_user_agent||'—'),actions]});$('adminPanel').innerHTML='<div class="adminSectionHead"><div><h3>Users</h3><div class="muted">Owner-only controls change roles, status, passwords and accounts.</div></div></div>'+adminTable(['Email','Role','Status','Registered','Last Login','IP','Device / Browser','Actions'],rows);$('adminPanel').querySelectorAll('[data-role-user]').forEach(e=>e.onchange=async()=>{if(!confirm('Change this user role?')){loadAdminUsers();return}const r=await adminFetch('/admin/users/'+e.dataset.roleUser+'/role',{method:'POST',body:JSON.stringify({role:e.value})});if(!r.ok)alert((await r.json()).error||'Failed');loadAdminUsers()});$('adminPanel').querySelectorAll('[data-status-user]').forEach(e=>e.onclick=async()=>{const r=await adminFetch('/admin/users/'+e.dataset.statusUser+'/status',{method:'POST',body:JSON.stringify({status:e.dataset.status})});if(!r.ok)alert((await r.json()).error||'Failed');loadAdminUsers()});$('adminPanel').querySelectorAll('[data-reset-user]').forEach(e=>e.onclick=async()=>{const pw=prompt('New password (8+ characters):');if(!pw)return;const r=await adminFetch('/admin/users/'+e.dataset.resetUser+'/password',{method:'POST',body:JSON.stringify({password:pw})});alert(r.ok?'Password updated.':((await r.json()).error||'Failed'))});$('adminPanel').querySelectorAll('[data-delete-user]').forEach(e=>e.onclick=async()=>{if(!confirm('Delete this user permanently?'))return;const r=await adminFetch('/admin/users/'+e.dataset.deleteUser,{method:'DELETE'});if(!r.ok)alert((await r.json()).error||'Failed');loadAdminUsers()})}
  function renderCreateUser(){const l=adminText();$('adminPanel').innerHTML=`<div class="card adminInner"><h3>${l.create}</h3><div class="grid two"><div><label>Email</label><input id="newUserEmail" type="email" placeholder="user@example.com" class="adminInput"><label style="display:block;margin-top:10px">Password</label><input id="newUserPassword" type="password" placeholder="8+ characters" class="adminInput"></div><div><label>Role</label><select id="newUserRole" class="adminInput">${roleOptions('user')}</select><div class="muted" style="margin-top:10px">Owner creation is protected by the backend. Passwords are hashed server-side.</div></div></div><button class="primary" id="createUserSubmit" style="margin-top:12px">${l.create}</button><div id="createUserMsg" class="muted" style="margin-top:10px"></div></div>`;$('createUserSubmit').onclick=async()=>{const email=$('newUserEmail').value.trim(),password=$('newUserPassword').value,role=$('newUserRole').value;const r=await adminFetch('/admin/users',{method:'POST',body:JSON.stringify({email,password,role})});const d=await r.json();$('createUserMsg').textContent=r.ok?'User created.':(d.error||'Creation failed');if(r.ok){$('newUserEmail').value='';$('newUserPassword').value='';loadAdminOverview()}}}
  async function loadAdminActivity(){const r=await adminFetch('/admin/activity');const d=await r.json();const rows=d.map(a=>[escHtml(a.email||'—'),escHtml(a.event_type),escHtml(a.route||'—'),escHtml(a.ip||'—'),escHtml(a.city&&a.country?(a.city+', '+a.country):(a.country||'—')),new Date(a.created_at).toLocaleString(),escHtml(a.user_agent||'—')]);$('adminPanel').innerHTML='<h3>Activity Log</h3>'+adminTable(['User','Event','Route','IP','Approx. Location','Time','Device'],rows)}
  async function loadAdminSecurity(){const r=await adminFetch('/admin/security');const d=await r.json();const rows=d.map(a=>[escHtml(a.email||a.user_email||'—'),escHtml(a.event_type),escHtml(a.ip||'—'),new Date(a.created_at).toLocaleString(),escHtml(a.user_agent||'—')]);$('adminPanel').innerHTML='<h3>Security Log</h3>'+adminTable(['Email','Event','IP','Time','Device'],rows)}
  async function loadAdminAudit(){const r=await adminFetch('/admin/audit');const d=await r.json();const rows=d.map(a=>[escHtml(a.actor_email||'—'),escHtml(a.action),escHtml(a.target_type||'—'),escHtml(a.target_id||'—'),escHtml(JSON.stringify(a.metadata||{})),new Date(a.created_at).toLocaleString()]);$('adminPanel').innerHTML='<h3>Administrative Audit</h3>'+adminTable(['Actor','Action','Target','ID','Metadata','Time'],rows)}
  async function loadAdminSystem(){const r=await adminFetch('/admin/system');const d=await r.json();const roles=d.roles.map(x=>[escHtml(x.role),x.count]);$('adminPanel').innerHTML='<h3>System</h3><div class="grid two"><div class="card"><div class="eyebrow">Backend</div><div class="big">'+escHtml(d.node)+'</div><div class="muted">Environment: '+escHtml(d.environment)+' · Database: '+(d.database?'OK':'OFF')+' · AI: '+(d.ai?'configured':'not configured')+'</div></div><div class="card"><h4>Users by Role</h4>'+adminTable(['Role','Count'],roles)+'</div></div>'}
  async function renderAdmin(){try{updateAdminLabels();await loadAdminOverview();await loadAdminUsers()}catch(e){if($('adminPanel'))$('adminPanel').innerHTML='<div class="feedback">Admin access required or backend/database is not configured.</div>';}}
  $('adminRefresh')?.addEventListener('click',()=>renderAdmin());$('adminUsersBtn')?.addEventListener('click',()=>loadAdminUsers().catch(()=>{}));$('adminCreateBtn')?.addEventListener('click',()=>renderCreateUser());$('adminActivityBtn')?.addEventListener('click',()=>loadAdminActivity().catch(()=>{}));$('adminSecurityBtn')?.addEventListener('click',()=>loadAdminSecurity().catch(()=>{}));$('adminAuditBtn')?.addEventListener('click',()=>loadAdminAudit().catch(()=>{}));$('adminSystemBtn')?.addEventListener('click',()=>loadAdminSystem().catch(()=>{}));
  async function checkAdminAccess(){if(!engineState.token){showAdminButton(false);return}try{const r=await api('/admin/overview');if(r.ok){const d=await r.json();engineState.role=d.role;engineState.email=engineState.email||d.email;persist();showAdminButton(true)}else showAdminButton(false)}catch{showAdminButton(false)}}
  window.vidoTrackRoute=async function(routeName){if(!engineState.token)return;api('/activity',{method:'POST',body:JSON.stringify({eventType:'view',route:routeName,metadata:{language:lang}})}).catch(()=>{})}
    const labels={de:{tutor:'✦ VIDO Tutor',account:'◉ Account & Sync',admin:'👑 Admin',tutor_title:'VIDO Tutor',tutor_subtitle:'Sokratischer IT-Lernassistent',tutor_context:'Aktuelle Aufgabe',tutor_ask:'Tutor fragen',tutor_response:'Tutor-Antwort',account_title:'Account & Sync',adaptive_title:'Adaptives Lernen & Spaced Repetition',adaptive_due:'Fällige Reviews',adaptive_next:'Nächste Auswahl',adaptive_start:'Adaptive Aufgabe starten'},en:{tutor:'✦ VIDO Tutor',account:'◉ Account & Sync',admin:'👑 Admin',tutor_title:'VIDO Tutor',tutor_subtitle:'Socratic IT learning assistant',tutor_context:'Current task',tutor_ask:'Ask Tutor',tutor_response:'Tutor response',account_title:'Account & Sync',adaptive_title:'Adaptive Learning & Spaced Repetition',adaptive_due:'Reviews due',adaptive_next:'Next selection',adaptive_start:'Start adaptive task'},ar:{tutor:'✦ مساعد VIDO',account:'◉ الحساب والمزامنة',tutor_title:'مساعد VIDO',tutor_subtitle:'مساعد تعليمي لتقنية المعلومات بطريقة سقراطية',tutor_context:'السؤال الحالي',tutor_ask:'اسأل المساعد',tutor_response:'رد المساعد',account_title:'الحساب والمزامنة',adaptive_title:'التعلم التكيفي والتكرار المتباعد',adaptive_due:'المراجعات المستحقة',adaptive_next:'الاختيار التالي',adaptive_start:'بدء سؤال تكيفي'}};
  function updateV2Labels(){const l=labels[lang]||labels.de;document.querySelectorAll('[data-route="tutor"]').forEach(b=>b.textContent=l.tutor);document.querySelectorAll('[data-route="account"]').forEach(b=>b.textContent=l.account);document.querySelectorAll('[data-route="admin"]').forEach(b=>b.textContent=l.admin);const map={tutor_title:'tutor_title',tutor_subtitle:'tutor_subtitle',tutor_context:'tutor_context',tutor_ask:'tutor_ask',tutor_response:'tutor_response',account_title:'account_title',adaptive_title:'adaptive_title',adaptive_due:'adaptive_due',adaptive_next:'adaptive_next',adaptive_start:'adaptive_start'};Object.entries(map).forEach(([id,k])=>{const e=document.querySelector('[data-i18n="'+id+'"]');if(e)e.textContent=l[k]});if($('accountEmail'))$('accountEmail').placeholder=lang==='ar'?'البريد الإلكتروني':lang==='en'?'Email':'E-Mail';if($('accountPassword'))$('accountPassword').placeholder=lang==='ar'?'كلمة المرور (8 أحرف على الأقل)':lang==='en'?'Password (8+ characters)':'Passwort (8+ Zeichen)';renderAdaptive()}
  $('langSelect')?.addEventListener('change',()=>setTimeout(updateV2Labels,0));updateV2Labels();
  const badge=document.createElement('span');badge.className='engineBadge';badge.textContent='Engine';document.querySelector('.top')?.appendChild(badge);api('/health').then(r=>r.json()).then(h=>{badge.textContent=h.database&&h.ai?'Backend + AI ✓':h.database?'Backend ✓':'Local Engine';badge.className='engineBadge '+(h.database?'healthOk':'healthWarn')}).catch(()=>{badge.textContent='Local Engine'});
  checkAdminAccess();
  document.documentElement.dataset.vidoEngine='v4-owner-admin';
  setTimeout(()=>{validateStoredSession();},0);
})();
